### PR TITLE
regression fixes

### LINKED ISSUE #192: crash in SendRoutingMessage
uninitialised memory access in `llarp::path::Path::SendRoutingMessage(const llarp::routing::IMessage* msg, llarp::router* r)`

`msg` is valid but points to garbage

this only happens when the endpoint is a service node

as far as i can tell, this does not affect hidden svc nodes. i am also unable to reproduce this bug on my old VMs. Because they are allowed to execute on any one (1) physical CPU by the hypervisor.

**update: multiprocessor systems only**
```
#0  0x0041cad0 in llarp::path::Path::SendRoutingMessage (this=0xac2bfb8, msg=0xac40050, r=0xac141a8) at ../llarp/path.cpp:589
#1  0x0044b550 in llarp::exit::BaseSession::Flush (this=0xac28170) at ../llarp/exit/session.cpp:195
#2  0x0043342c in llarp::service::Endpoint::FlushSNodeTraffic (this=0xcb90020) at ../llarp/service/endpoint.cpp:132
#3  0x00453fba in llarp::handlers::TunEndpoint::tunifBeforeWrite (tun=0xcb914c0) at ../llarp/handlers/tun.cpp:647
#4  0x004e91f9 in win32_tun_io::flush_write (this=0xac22628) at ../llarp/ev_win32.hpp:144
#5  0x004677bb in tun_ev_loop@4 (unused=0x0) at ../llarp/ev_win32.hpp:204
#6  0x749e60c9 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#7  0x771f6004 in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#8  0x771f5fd4 in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#9  0x00000000 in ?? ()
```
```
>>> p msg
$1 = (const llarp::routing::IMessage *) 0xc4cbec0
>>> p *msg
$2 = {
  <llarp::IBEncodeMessage> = {
    _vptr.IBEncodeMessage = 0xbaadf00d, <-- special pattern used by NT kernel allocator
    version = 13451671603782742029
  },
  members of llarp::routing::IMessage:
  from = {
    static SIZE = 16,
    val = {
      __data = "\r▒\r▒\r▒\r▒",
      __align = {<No data fields>}
    }
  },
  S = 7
}
```

### PR DESCRIPTION
**Pull request by despair86**
- fix #192 hopefully (beaudan seems to agree)
- strip some dead code (and require a proper C++11 toolset for windows)
- abseil platform checks for [net|open]bsd
- fix regression in windows installer (tap driver install)
- clang-format

### CODE REVIEW

File: llarp/util/bencode.cpp [hunk 1]
```diff
@@ -75,14 +75,10 @@ bencode_write_bytestring(llarp_buffer_t* buff, const void* data, size_t sz)
 bool
 bencode_write_uint64(llarp_buffer_t* buff, uint64_t i)
 {
-#ifndef __LP64__
-  if(!buff->writef("i%llu", i))
-#else
-#if(__APPLE__ && __MACH__)
+#if !defined(__LP64__) || (__APPLE__ && __MACH__)
```
Comment (michael-loki) [inline llarp/util/bencode.cpp]: 🥇 💯

Comment (despair86) [reply llarp/util/bencode.cpp]: heh
